### ISSUE TITLE
ES5IdentifierNames.java doesn't load correctly from classpath as a webapp

### ISSUE THREAD

**Issue by St0n3Gh0st** [jshaptic/jshint-javaport#2]
When packaged into a webapp (i.e. WAR file), the approach that `ES5IdentifierNames.java` takes to load a resource file from the classpath using the default classloader doesn't work:

`ClassLoader.getSystemResourceAsStream("es5-identifier-names.txt");`

I believe the classloader would need to be the context class loader instead, e.g.

```
ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
classLoader.getResourceAsStream("es5-identifier-names.txt");
```

This problem and solution is explained in more detail at https://stackoverflow.com/questions/2522235/getsystemresourceasstream-returns-null

**Comment by jshaptic** [comment]
Thanks @abonstu and @St0n3Gh0st, this issue is fixed. Check latest version 2.10.1.2
